title:               My digital garden
#include:             ['_pages']

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /notes/:path.html
  pages:
    output: true
    permalink: /pages/:name.html
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:slug.html

defaults:
  - scope:
      path: "**/*.html"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
